# Generated by Django 5.2 on 2025-04-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_validated_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_validated',
            new_name='is_verified',
        ),
    ]
