# Generated by Django 3.2.25 on 2024-10-23 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241020_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('bread', 'Bread'), ('eggs_and_dairy', 'Eggs & Dairy'), ('fats_and_oils', 'Fats & Oils'), ('fish', 'Fish'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('herbs_spices', 'Herbs & Spices'), ('meat', 'Meat'), ('nuts', 'Nuts'), ('pasta_rice', 'Pasta & Rice'), ('vegetables', 'Vegetables'), ('others', 'Others')], default='others', max_length=32)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('ml', 'millilitres')], default='g', max_length=8)),
                ('alt_unit', models.CharField(choices=[('piece', 'pieces'), ('pinch', 'pinches'), ('spoon', 'spoons')], max_length=8, null=True)),
                ('alt_to_unit_conversion', models.PositiveIntegerField(null=True)),
                ('kcal_per_100_units', models.PositiveIntegerField()),
                ('excluded_tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe')),
            ],
        ),
    ]
