# Generated by Django 3.2.25 on 2024-10-23 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alt_to_unit_conversion',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='alt_unit',
            field=models.CharField(choices=[('piece', 'pieces'), ('spoon', 'spoons'), ('pinch', 'pinches')], max_length=8, null=True),
        ),
    ]
