# Generated by Django 3.2.25 on 2024-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241023_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alt_to_unit_conversion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='alt_unit',
            field=models.CharField(blank=True, choices=[('piece', 'pieces'), ('spoon', 'spoons'), ('pinch', 'pinches')], max_length=8, null=True),
        ),
    ]
