# Generated by Django 3.2.25 on 2024-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241023_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='excluded_tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
