# Generated by Django 3.2.25 on 2024-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ingredient_excluded_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
