# Generated by Django 3.2.25 on 2024-10-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ingredient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
