# Generated by Django 3.2.25 on 2024-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('american', 'American'), ('chinese', 'Chinese'), ('french', 'French'), ('greek', 'Greek'), ('indian', 'Indian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('lebanese', 'Lebanese'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('vietnamese', 'Vietnamese'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('cold_beverage', 'Cold beverage'), ('dinner', 'Dinner'), ('hot_beverage', 'Hot beverage'), ('snack', 'Snack'), ('soup', 'Soup'), ('sweet', 'Sweet'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
