# Generated by Django 3.2.25 on 2024-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20241028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('cold_beverage', 'Cold beverage'), ('dessert', 'Dessert'), ('hot_beverage', 'Hot beverage'), ('main', 'Main'), ('snack', 'Snack'), ('soup', 'Soup'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
