# Generated by Django 3.2.25 on 2024-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='_steps',
            field=models.TextField(default='no_step'),
            preserve_default=False,
        ),
    ]
