# Generated by Django 4.2.19 on 2025-03-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
